CoreAndFood/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreAndFood.Data.Models;
using CoreAndFood.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace CoreAndFood.Controllers
{
    public class CategoryController : Controller
    {
        CategoriRepository categoriRepository = new CategoriRepository();
        public IActionResult Index()
        {
          
            return View(categoriRepository.TList());
        }
        [HttpGet]
        public IActionResult CategoryAdd()
        {
            return View();
        }
       [HttpPost]
        public IActionResult CategoryAdd(Category p)
        {
            if (!ModelState.IsValid)
            {
                return View("CategoryAdd");
            }
            categoriRepository.TAdd(p);
            return RedirectToAction("Index");
        }
        public IActionResult CategoryGet(int id)
        {
            var x = categoriRepository.GetT(id);
            Category ct = new Category()
            {
                CatgoryName = x.CatgoryName,
                CatgoryDescription = x.CatgoryDescription,
                CatgoryID = x.CatgoryID
            };
            return View(ct);
        }
        [HttpPost]
        public IActionResult CategoryUpdate(Category p)
        {
            var x = categoriRepository.GetT(p.CatgoryID);
            x.CatgoryName = p.CatgoryName;
            x.CatgoryDescription = p.CatgoryDescription;
            x.Status = p.Status;
            categoriRepository.TUpdate(x);
            return RedirectToAction("Index");
        }

        public IActionResult CategoryDelete(int id)
        {
            var x = categoriRepository.GetT(id);
            x.Status = false;
            categoriRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
    }
}

CoreAndFood/Controllers/ChartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreAndFood.Data;
using CoreAndFood.Data.Models;
using Microsoft.AspNetCore.Mvc;

namespace CoreAndFood.Controllers
{
    public class ChartController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult VisualizeProductResult()
        {
            return Json(FoodList());
        }
        public List<Class1> FoodList()
        {
            List<Class1> cs = new List<Class1>();
            using (var c = new Context())
            {
                cs = c.Foods.Select(x => new Class1
                {

                    FoodName = x.Name,
                    stock = x.Stock
                }).ToList();
            }
            return cs;
        }
        public IActionResult Statick()
        {
            Context c = new Context();
            var deger1 = c.Foods.Count();
            var deger2 = c.Categories.Count();
            var foid = c.Categories.Where(x => x.CatgoryName == "Fruit").Select(y => y.CatgoryID).FirstOrDefault();
            var deger3 = c.Foods.Where(x => x.CategoryID == foid).Count();
            var deger4 = c.Foods.Where(x => x.CategoryID == (c.Categories.Where(z =>z.CatgoryName == "Vegetables").Select(y => y.CatgoryID).FirstOrDefault())).Count();
            var deger5 = c.Foods.Sum(x => x.Stock);
            var deger6 = c.Foods.OrderByDescending(x => x.Stock).Select(y => y.Name).FirstOrDefault();
            var deger7 = c.Foods.OrderBy(x => x.Stock).Select(y => y.Name).FirstOrDefault();
            var deger8 = c.Foods.Average(x => x.Price).ToString("0.00"); 
            ViewBag.d1 = deger1;
            ViewBag.d2 = deger2;
            ViewBag.d3 = deger3;
            ViewBag.d4 = deger4;
            ViewBag.d5 = deger5;
            ViewBag.d6 = deger6;
            ViewBag.d7 = deger7;
            ViewBag.d8 = deger8;
            return View();
        }
    }
}

CoreAndFood/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CoreAndFood.Data.Models;
using CoreAndFood.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;

namespace CoreAndFood.Controllers
{
    public class FoodController : Controller
    {
        FoodRepository foodRepository = new FoodRepository();
        Context c = new Context();
        public IActionResult Index(int page=1)
        {

            return View(foodRepository.TList("Category").ToPagedList(page,3));
        }
        [HttpGet]
        public IActionResult FoodAdd()
        {
            List<SelectListItem> values = (from x in c.Categories.ToList() select new SelectListItem { Text = x.CatgoryName, Value = x.CatgoryID.ToString() }).ToList();
            ViewBag.vls = values;
            return View();
        }
        [HttpPost]
        public IActionResult FoodAdd(Food f)
        {
            if (!ModelState.IsValid)
            {
                return View("FoodAdd");
            }
            foodRepository.TAdd(f);
            return RedirectToAction("Index");
        }
        public IActionResult FoodDelete(int id)
        {
            foodRepository.TDelete(new Food { FoodID = id });
            return RedirectToAction("Index");
        }

        public IActionResult FoodGet(int id)
        {
            var x = foodRepository.GetT(id);
            List<SelectListItem> values = (from a in c.Categories.ToList() select new SelectListItem { Text = a.CatgoryName, Value = a.CatgoryID.ToString() }).ToList();
            ViewBag.vls = values;
            Food fd = new Food()
            {
                Name = x.Name,
                Description = x.Description,
                Price = x.Price,
                Stock = x.Stock,
                CategoryID = x.CategoryID,
                ImageUrl = x.ImageUrl,
                FoodID = x.FoodID
            };
            return View(fd);
        }
        [HttpPost]
        public IActionResult FoodUpdate(Food p)
        {
            var x = foodRepository.GetT(p.FoodID);
            x.Name = p.Name;
            x.Description = p.Description;
            x.Price = p.Price;
            x.Stock = p.Stock;
            x.CategoryID = p.CategoryID;
            foodRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
    }
}

CoreAndFood/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CoreAndFood.Data.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoreAndFood.Controllers
{
    public class LoginController : Controller
    {
        Context c = new Context();
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }
        [AllowAnonymous]
        [HttpPost]
        public async Task<IActionResult>  Index (Admin p)
        {
            var datavalue = c.Admins.FirstOrDefault(x => x.UserName == p.UserName && x.Password == p.Password);
            if (datavalue!=null)
            {
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name,p.UserName)
                };
                var useridentiy = new ClaimsIdentity(claims, "Login");
                ClaimsPrincipal principal = new ClaimsPrincipal(useridentiy);
                await HttpContext.SignInAsync(principal);
              return  RedirectToAction("Index","Category");
            }
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index","Login");
        }
    }
}

CoreAndFood/Controllers/OnyuzController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CoreAndFood.Controllers
{
    public class OnyuzController : Controller
    {
        [AllowAnonymous]
        public IActionResult Index()
        {
            return View();
        }
    }
}

CoreAndFood/Views/Category/CategoryAdd.cshtml
@model CoreAndFood.Data.Models.Category
@{
    ViewData["Title"] = "CategoryAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Category Add Page</h2>
<br />
@using (Html.BeginForm("CategoryAdd", "Category", FormMethod.Post))
{
    @Html.LabelFor(x => x.CatgoryName, "Category Name")
    @Html.TextBoxFor(x => x.CatgoryName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x=>x.CatgoryName,"",new { @style="color:red"})
    <br />
    @Html.LabelFor(x => x.CatgoryDescription, "Category Description")
    @Html.TextBoxFor(x => x.CatgoryDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Save</button>
}

CoreAndFood/Views/Category/CategoryGet.cshtml
@model CoreAndFood.Data.Models.Category
@{
    ViewData["Title"] = "CategoryGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Category Add Page</h2>
<br />
@using (Html.BeginForm("CategoryUpdate", "Category", FormMethod.Post))
{
    @Html.LabelFor(x => x.CatgoryID, "Category ID")
    @Html.TextBoxFor(x => x.CatgoryID, new { @class = "form-control" })

    @Html.LabelFor(x => x.Status)
    @Html.TextBoxFor(x => x.Status, new { @class = "form-control" })

    @Html.LabelFor(x => x.CatgoryName, "Category Name")
    @Html.TextBoxFor(x => x.CatgoryName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CatgoryName, "", new { @style = "color:red" })
    <br />
    @Html.LabelFor(x => x.CatgoryDescription, "Category Description")
    @Html.TextBoxFor(x => x.CatgoryDescription, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Update</button>
}

CoreAndFood/Views/Category/Index.cshtml
@model List< CoreAndFood.Data.Models.Category>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Category List</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>STATUS</th>
        <th>CATEGORY NAME</th>
        <th>DELETE</th>
        <th>UPDATE</th>
    </tr>
    @foreach (var x in Model)


    {
    <tr>
        <td>@x.CatgoryID</td>
        <td>@x.Status</td>
        <td>@x.CatgoryName</td>
        <td><a href="/Category/CategoryDelete/@x.CatgoryID" class="btn btn-danger">DELETE</a>
        <td><a href="/Category/CategoryGet/@x.CatgoryID" class="btn btn-success"> UPDATE</a>
    </tr>
            }
      
    </table>
<a href=" /Category/CategoryAdd" class="btn btn-primary">New Category</a>

CoreAndFood/Views/Chart/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!DOCTYPE html>
<html lang="en">
<head>
    <title>Result Visualization</title>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $.ajax({
                type: "POST",
                dataType: "json",
                contentType: "application/json",
                url: '@Url.Action("VisualizeUrunResult", "Chart")',
                success: function (result) {
                    google.charts.load('current', {
                        'packages': ['corechart']
                    });
                    google.charts.setOnLoadCallback(function () {
                        drawChart(result);
                    });
                }
            });
        });

        function drawChart(result) {
            var data = new google.visualization.DataTable();
            data.addColumn('string', 'Name');
            data.addColumn('number', 'Stoklar');
            var dataArray = [];

            $.each(result, function (i, obj) {
                dataArray.push([obj.ad, obj.sayi]);
            });
            data.addRows(dataArray);

            var columnChartOptions = {
                title: "Ürün - Stok Grafiği",
                width: 1000,
                height: 400,
                bar: { groupWidth: "20%" },
            };

            var columnChart = new google.visualization.PieChart(document
                .getElementById('Piechart_div'));

            columnChart.draw(data, columnChartOptions);
        }
    </script>
</head>
<body>
    <div id="Piechart_div"></div>
</body>
</html>

CoreAndFood/Views/Chart/Statick.cshtml
@{
    ViewData["Title"] = "Statick";
    Layout = "~/Views/Shared/_Layout.cshtml";
}



<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
    <!-- Custom Theme files -->
    <link href="~/web2/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <!-- Custom Theme files -->
    <script src="~/web2/js/jquery.min.js"></script>
    <link rel="stylesheet" href="~/web2/css/font-awesome.css">
    <!-- Custom Theme files -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Metro Panel Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!--webfont-->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href="~/web2/css/jqvmap.css" media="screen" rel="stylesheet" type="text/css" />

    <script src="~/web2/js/easyResponsiveTabs.js" type="text/javascript"></script>
    <script src="~/web2/js/main.js"></script> <!-- Resource jQuery -->
    <!-- chart -->
    <script src="~/web2/js/Chart1.js"></script>
    <!-- //chart -->
</head>
<body>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#1abc9c">
                <div class="icon-text">
                    <h3>@ViewBag.d1</h3>
                    <p>Total Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#2ecc71">
                <div class="icon-text">
                    <h3>@ViewBag.d2</h3>
                    <p>Total Category</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#3498db">
                <div class="icon-text">
                    <h3>@ViewBag.d3 </h3>
                    <p>Fruit Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#9b59b6">
                <div class="icon-text">
                    <h3>@ViewBag.d4</h3>
                    <p>Vegetable Count</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="total-content">
        <div class="list_of_members">
            <div class="sales" style="background-color:#16a085">
                <div class="icon-text">
                    <h3>@ViewBag.d5</h3>
                    <p>Sum Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="new-users" style="background-color:#27ae60">
                <div class="icon-text">
                    <h3>@ViewBag.d8</h3>
                    <p>Food Average</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="orders" style="background-color:#2980b9">
                <div class="icon-text">
                    <h3>@ViewBag.d6</h3>
                    <p>Max Stock Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="visitors" style="background-color:#8e44ad">
                <div class="icon-text">
                    <h3>@ViewBag.d7</h3>
                    <p>Min Stock Food</p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix"></div>
        </div>
    </div>

    <div class="clearfix"></div>
    
    <div class="clearfix"></div>
    
</body>
</html>

CoreAndFood/Views/Food/FoodAdd.cshtml
@model CoreAndFood.Data.Models.Food
@{
    ViewData["Title"] = "FoodAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food Add Page</h2>
<br />
@using (Html.BeginForm("FoodAdd", "Food", FormMethod.Post))
{
    @Html.LabelFor(x => x.Name, "Food Name")
    @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Stock)
    @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Price)
    @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.ImageUrl)
    @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Category)
    @Html.DropDownListFor(x => x.CategoryID,(List<SelectListItem>)ViewBag.vls, new { @class = "form-control" })
    <br />
    @Html.LabelFor(x => x.Description)
    @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Save</button>
}

CoreAndFood/Views/Food/FoodGet.cshtml
@model CoreAndFood.Data.Models.Food
@{
    ViewData["Title"] = "FoodGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("FoodUpdate", "Food", FormMethod.Post))
{
    
        @Html.LabelFor(x => x.FoodID, "Food ID")
        @Html.TextBoxFor(x => x.FoodID, new { @class = "form-control" })

        @Html.LabelFor(x => x.Name, "Food Name")
        @Html.TextBoxFor(x => x.Name, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Stock)
        @Html.TextBoxFor(x => x.Stock, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Price)
        @Html.TextBoxFor(x => x.Price, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.ImageUrl)
        @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Category)
        @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vls, new { @class = "form-control" })
        <br />
        @Html.LabelFor(x => x.Description)
        @Html.TextAreaFor(x => x.Description, new { @class = "form-control" })
        <br />
        <button class="btn btn-success">Update</button>

    }

CoreAndFood/Views/Food/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core
@model IPagedList<CoreAndFood.Data.Models.Food>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food List</h2>
<br />
<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>FOOD NAME</th>
        <th>PRICE</th>
        <th>STOCK</th>
        <th>CATEGORY</th>
        <th>DELETE</th>
        <th>UPDATE</th>
        <th>DETAILS</th>
    </tr>
    @foreach (var x in Model)


    {
    <tr>
        <td>@x.FoodID</td>
        <td>@x.Name</td>
        <td>@x.Price</td>
        <td>@x.Stock</td>
        <td>@x.Category.CatgoryName</td>
        <td><a href="/Food/FoodDelete/@x.FoodID" class="btn btn-danger">DELETE</a>
        <td><a href="/Food/FoodGet/@x.FoodID" class="btn btn-success"> UPDATE</a>
        <td><a href="#" class="btn btn-warning"> DETAILS</a>
    </tr>
    }

</table>
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new { page}))
<a href=" /Food/FoodAdd" class="btn btn-primary">New Food</a>

CoreAndFood/Views/Login/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Login V6</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--===============================================================================================-->
    <link rel="icon" type="image/png" href="/LoginTemplate/images/icons/favicon.ico" />
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/LoginTemplate/vendor/bootstrap/css/bootstrap.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/LoginTemplate/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/LoginTemplate/fonts/iconic/css/material-design-iconic-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/LoginTemplate/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/LoginTemplate/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/LoginTemplate/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/LoginTemplate/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/LoginTemplate/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="/LoginTemplate/css/util.css">
    <link rel="stylesheet" type="text/css" href="/LoginTemplate/css/main.css">
    <!--===============================================================================================-->
</head>
<body>

    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100 p-t-85 p-b-20">
                <form class="login100-form validate-form"action="~/Login/Index"method="post">
                    <span class="login100-form-title p-b-70">
                       Core And Food
                    </span>
                    <span class="login100-form-avatar">
                       
                    </span>

                    <div class="wrap-input100 validate-input m-t-85 m-b-35" data-validate="Enter username">
                        <input class="input100" type="text" name="Username">
                        <span class="focus-input100" data-placeholder="Kullanıcı Adınız"></span>
                    </div>

                    <div class="wrap-input100 validate-input m-b-50" data-validate="Enter password">
                        <input class="input100" type="password" name="Password">
                        <span class="focus-input100" data-placeholder="Şifreniz"></span>
                    </div>

                    <div class="container-login100-form-btn">
                        <button class="login100-form-btn">
                            Login
                        </button>
                    </div>

                    <ul class="login-more p-t-190">
                  
                        <li>
                            <a href="#" class="txt2">
                                return to showcase
                            </a>
                        </li>
                    </ul>
                </form>
            </div>
        </div>
    </div>


    <div id="dropDownSelect1"></div>

    <!--===============================================================================================-->
    <script src="/LoginTemplate/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
    <script src="/LoginTemplate/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script src="/LoginTemplate/vendor/bootstrap/js/popper.js"></script>
    <script src="/LoginTemplate/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script src="/LoginTemplate/vendor/select2/select2.min.js"></script>
    <!--===============================================================================================-->
    <script src="/LoginTemplate/vendor/daterangepicker/moment.min.js"></script>
    <script src="/LoginTemplate/vendor/daterangepicker/daterangepicker.js"></script>
    <!--===============================================================================================-->
    <script src="/LoginTemplate/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script src="/LoginTemplate/js/main.js"></script>

</body>
</html>

CoreAndFood/Views/Onyuz/Components/CategoryGet/Default.cshtml
@model IEnumerable<CoreAndFood.Data.Models.Category>

<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
    <ul class="nav navbar-nav nav_1">
        @foreach (var item in Model)
        {
            <li><a href="products.html">@item.CatgoryName</a></li>
        }

    </ul>
</div>

CoreAndFood/Views/Onyuz/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_OnyuzLayout.cshtml";
}

CoreAndFood/Views/Shared/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Core And Food</a>
            </div>
            <ul class="nav navbar-nav">
                <li><a href="/Category/Index">Category</a></li>
                <li><a href="/Food/Index"> Food</a></li>
                <li><a href="#">Charts</a></li>
                <li><a href="#">Popup</a></li>
                <li><a href="/Chart/Statick">Statics</a></li>
                <li><a href="#">Settings</a></li>
                <li><a href="/Login/LogOut">Log Out</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
      @RenderBody()
    </div>

</body>
</html>